"""Layer 7 — Export Engine. Renders planogram_json to JPEG (Pillow) and PPTX (python-pptx)."""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from PIL import Image, ImageDraw, ImageFont
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.util import Emu, Inches, Pt

JPEG_WIDTH = 1800
JPEG_HEIGHT = 1200
HEADER_HEIGHT = 100
FOOTER_HEIGHT = 80
SHELF_LEFT_MARGIN = 180
SHELF_RIGHT_MARGIN = 40
JPEG_QUALITY = 92

TIER_LABELS = {
    "top_level": "Top Level",
    "eye_level": "Eye Level",
    "mid_level": "Mid Level",
    "low_level": "Low Level",
}


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    color = (hex_color or "#95A5A6").lstrip("#")
    if len(color) != 6:
        return (149, 165, 166)
    try:
        return tuple(int(color[i : i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]
    except ValueError:
        return (149, 165, 166)


def _is_dark(rgb: tuple[int, int, int]) -> bool:
    # Perceived luminance (Rec. 709)
    r, g, b = rgb
    return (0.2126 * r + 0.7152 * g + 0.0722 * b) < 140


def _load_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    candidates = (
        ["/System/Library/Fonts/Supplemental/Arial Bold.ttf", "/Library/Fonts/Arial Bold.ttf"]
        if bold
        else ["/System/Library/Fonts/Supplemental/Arial.ttf", "/Library/Fonts/Arial.ttf"]
    )
    candidates += [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except (OSError, IOError):
            continue
    return ImageFont.load_default()


def _truncate_to_width(draw: ImageDraw.ImageDraw, text: str, font: Any, max_width: int) -> str:
    if not text:
        return ""
    if draw.textlength(text, font=font) <= max_width:
        return text
    ellipsis = "..."
    while text and draw.textlength(text + ellipsis, font=font) > max_width:
        text = text[:-1]
    return (text + ellipsis) if text else ""


def _store_label(planogram_json: dict[str, Any], store_name: str | None) -> str:
    name = (store_name or "Store").strip()
    level = planogram_json.get("generation_level") or "store"
    return f"{name}  |  {level.title()} Planogram"


def render_planogram_to_jpeg(planogram_json: dict[str, Any], store_name: str | None = None) -> bytes:
    """Render the planogram to a JPEG. Returns raw JPEG bytes."""
    shelf_config = planogram_json.get("shelf_config") or {}
    shelves = planogram_json.get("shelves") or []
    confidence = planogram_json.get("confidence") or {}
    category_summary = planogram_json.get("category_summary") or {}

    shelf_width_cm = float(shelf_config.get("shelf_width_cm") or 180.0)
    shelf_count = int(shelf_config.get("shelf_count") or max(len(shelves), 1))

    image = Image.new("RGB", (JPEG_WIDTH, JPEG_HEIGHT), "white")
    draw = ImageDraw.Draw(image)

    title_font = _load_font(36, bold=True)
    subtitle_font = _load_font(20)
    small_font = _load_font(16)
    tiny_font = _load_font(13)
    sku_font = _load_font(14, bold=True)

    # Header
    draw.text((40, 30), _store_label(planogram_json, store_name), fill="#1A2332", font=title_font)
    generated_at = planogram_json.get("generated_at") or datetime.utcnow().isoformat()
    draw.text(
        (40, 70),
        f"Generated by Eureka  •  {generated_at[:10]}  •  Confidence: {confidence.get('tier', 'unknown').title()}",
        fill="#4A5568",
        font=subtitle_font,
    )
    draw.line([(40, HEADER_HEIGHT - 4), (JPEG_WIDTH - 40, HEADER_HEIGHT - 4)], fill="#1A2332", width=2)

    # Shelf area
    canvas_top = HEADER_HEIGHT + 20
    canvas_bottom = JPEG_HEIGHT - FOOTER_HEIGHT - 20
    shelf_area_height = canvas_bottom - canvas_top
    shelf_height_px = shelf_area_height // max(shelf_count, 1)
    shelf_drawable_width = JPEG_WIDTH - SHELF_LEFT_MARGIN - SHELF_RIGHT_MARGIN

    # Sort shelves by shelf_number ascending so shelf 1 appears at the top
    sorted_shelves = sorted(shelves, key=lambda s: int(s.get("shelf_number") or 0))

    for index, shelf in enumerate(sorted_shelves):
        shelf_top = canvas_top + index * shelf_height_px
        shelf_bottom = shelf_top + shelf_height_px

        # Shelf line
        draw.line(
            [(SHELF_LEFT_MARGIN, shelf_bottom - 2), (JPEG_WIDTH - SHELF_RIGHT_MARGIN, shelf_bottom - 2)],
            fill="#CCCCCC",
            width=2,
        )

        tier = str(shelf.get("tier") or "mid_level")
        shelf_number = shelf.get("shelf_number") or (index + 1)
        label = f"Shelf {shelf_number}\n{TIER_LABELS.get(tier, tier.title())}"
        draw.text((30, shelf_top + 12), label, fill="#1A2332", font=small_font)

        # Products
        for product in shelf.get("products") or []:
            position_x_cm = float(product.get("position_x_cm") or 0.0)
            total_width_cm = float(product.get("total_width_cm") or product.get("width_cm") or 10.0)
            x = SHELF_LEFT_MARGIN + (position_x_cm / shelf_width_cm) * shelf_drawable_width
            w = max(8.0, (total_width_cm / shelf_width_cm) * shelf_drawable_width)
            y = shelf_top + 6
            h = shelf_height_px - 14

            fill_rgb = _hex_to_rgb(str(product.get("color_hex") or "#95A5A6"))
            draw.rectangle([(x, y), (x + w, y + h)], fill=fill_rgb, outline="#1A2332", width=1)

            text_color = "white" if _is_dark(fill_rgb) else "#1A2332"
            inner_pad = 6
            text_max_width = int(max(0, w - 2 * inner_pad))

            sku_text = _truncate_to_width(draw, str(product.get("sku") or ""), sku_font, text_max_width)
            name_text = _truncate_to_width(draw, str(product.get("name") or ""), tiny_font, text_max_width)
            facing_count = int(product.get("facing_count") or 1)

            if sku_text:
                draw.text((x + inner_pad, y + inner_pad), sku_text, fill=text_color, font=sku_font)
            if name_text:
                draw.text((x + inner_pad, y + inner_pad + 18), name_text, fill=text_color, font=tiny_font)
            if w > 60:
                facings_label = f"x{facing_count}"
                facing_w = draw.textlength(facings_label, font=tiny_font)
                draw.text(
                    (x + w - inner_pad - facing_w, y + h - inner_pad - 14),
                    facings_label,
                    fill=text_color,
                    font=tiny_font,
                )

    # Footer: category legend
    footer_top = JPEG_HEIGHT - FOOTER_HEIGHT
    draw.line([(40, footer_top), (JPEG_WIDTH - 40, footer_top)], fill="#E2E8F0", width=1)

    legend_x = 40
    legend_y = footer_top + 14
    swatch = 18
    for category, values in list(category_summary.items())[:8]:
        # Find a representative color from the shelves
        color_hex = "#95A5A6"
        for shelf in shelves:
            for product in shelf.get("products") or []:
                if str(product.get("category") or "").lower() == str(category).lower():
                    color_hex = str(product.get("color_hex") or color_hex)
                    break
        rgb = _hex_to_rgb(color_hex)
        draw.rectangle([(legend_x, legend_y), (legend_x + swatch, legend_y + swatch)], fill=rgb, outline="#1A2332")
        label = f"{category.title()} ({values.get('sku_count', 0)})"
        draw.text((legend_x + swatch + 6, legend_y + 1), label, fill="#1A2332", font=small_font)
        legend_x += int(swatch + 14 + draw.textlength(label, font=small_font))
        if legend_x > JPEG_WIDTH - 200:
            break

    # Right-aligned summary
    sku_count = sum(len(s.get("products") or []) for s in shelves)
    summary = f"SKUs placed: {sku_count}  •  Confidence: {confidence.get('tier', 'unknown').title()} ({float(confidence.get('score') or 0):.2f})"
    summary_w = draw.textlength(summary, font=small_font)
    draw.text((JPEG_WIDTH - 40 - summary_w, footer_top + 44), summary, fill="#4A5568", font=small_font)

    # Draft watermark for low confidence
    if str(confidence.get("tier") or "").lower() == "low":
        watermark_font = _load_font(80, bold=True)
        wm_text = "DRAFT — LOW CONFIDENCE"
        wm = Image.new("RGBA", image.size, (0, 0, 0, 0))
        wm_draw = ImageDraw.Draw(wm)
        wm_w = wm_draw.textlength(wm_text, font=watermark_font)
        wm_draw.text(
            ((JPEG_WIDTH - wm_w) / 2, JPEG_HEIGHT / 2 - 50),
            wm_text,
            fill=(231, 76, 60, 80),
            font=watermark_font,
        )
        rotated = wm.rotate(15, resample=Image.BICUBIC)
        image.paste(rotated, (0, 0), rotated)

    buffer = io.BytesIO()
    image.save(buffer, format="JPEG", quality=JPEG_QUALITY)
    return buffer.getvalue()


def _set_shape_fill(shape, hex_color: str) -> None:
    rgb = _hex_to_rgb(hex_color)
    shape.fill.solid()
    shape.fill.fore_color.rgb = RGBColor(*rgb)
    shape.line.color.rgb = RGBColor(26, 35, 50)
    shape.line.width = Emu(9525)  # ~0.75pt


def _set_shape_text(shape, sku: str, name: str, facing_count: int, dark_fill: bool) -> None:
    tf = shape.text_frame
    tf.word_wrap = True
    tf.margin_left = Emu(36000)
    tf.margin_right = Emu(36000)
    tf.margin_top = Emu(36000)
    tf.margin_bottom = Emu(36000)

    color = RGBColor(255, 255, 255) if dark_fill else RGBColor(26, 35, 50)

    p = tf.paragraphs[0]
    p.text = sku or ""
    for run in p.runs:
        run.font.bold = True
        run.font.size = Pt(9)
        run.font.color.rgb = color

    if name:
        p2 = tf.add_paragraph()
        p2.text = name[:40]
        for run in p2.runs:
            run.font.size = Pt(7)
            run.font.color.rgb = color

    if facing_count > 1:
        p3 = tf.add_paragraph()
        p3.text = f"x{facing_count}"
        for run in p3.runs:
            run.font.size = Pt(7)
            run.font.italic = True
            run.font.color.rgb = color


def render_planogram_to_pptx(planogram_json: dict[str, Any], store_name: str | None = None) -> bytes:
    """Render the planogram as a 3-slide PPTX. Returns raw bytes."""
    shelf_config = planogram_json.get("shelf_config") or {}
    shelves = planogram_json.get("shelves") or []
    confidence = planogram_json.get("confidence") or {}
    assortment = planogram_json.get("assortment") or {}
    warnings = planogram_json.get("data_quality_warnings") or []
    category_summary = planogram_json.get("category_summary") or {}

    shelf_width_cm = float(shelf_config.get("shelf_width_cm") or 180.0)
    shelf_count = int(shelf_config.get("shelf_count") or max(len(shelves), 1))

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    blank_layout = prs.slide_layouts[6]

    # ---- Slide 1: Title ----
    slide_one = prs.slides.add_slide(blank_layout)
    bg = slide_one.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height)
    bg.fill.solid()
    bg.fill.fore_color.rgb = RGBColor(26, 35, 50)
    bg.line.fill.background()

    title_box = slide_one.shapes.add_textbox(Inches(0.6), Inches(2.4), Inches(12.0), Inches(1.5))
    title_tf = title_box.text_frame
    title_tf.word_wrap = True
    title_p = title_tf.paragraphs[0]
    title_p.text = (store_name or "Store").strip()
    for run in title_p.runs:
        run.font.size = Pt(48)
        run.font.bold = True
        run.font.color.rgb = RGBColor(255, 255, 255)

    subtitle_p = title_tf.add_paragraph()
    subtitle_p.text = f"{(planogram_json.get('generation_level') or 'store').title()}-level Planogram"
    for run in subtitle_p.runs:
        run.font.size = Pt(24)
        run.font.color.rgb = RGBColor(200, 213, 230)

    meta_box = slide_one.shapes.add_textbox(Inches(0.6), Inches(4.2), Inches(12.0), Inches(0.8))
    meta_p = meta_box.text_frame.paragraphs[0]
    generated_at = (planogram_json.get("generated_at") or datetime.utcnow().isoformat())[:10]
    meta_p.text = f"Generated by Eureka  •  {generated_at}"
    for run in meta_p.runs:
        run.font.size = Pt(16)
        run.font.color.rgb = RGBColor(200, 213, 230)

    # Confidence badge corner
    badge = slide_one.shapes.add_shape(
        MSO_SHAPE.ROUNDED_RECTANGLE, Inches(10.5), Inches(0.5), Inches(2.5), Inches(0.7)
    )
    tier = str(confidence.get("tier") or "unknown").lower()
    badge_color = {"high": (39, 174, 96), "medium": (243, 156, 18), "low": (231, 76, 60)}.get(tier, (149, 165, 166))
    badge.fill.solid()
    badge.fill.fore_color.rgb = RGBColor(*badge_color)
    badge.line.fill.background()
    badge_p = badge.text_frame.paragraphs[0]
    badge_p.text = f"Confidence: {tier.title()} ({float(confidence.get('score') or 0):.2f})"
    badge_p.alignment = 2  # center
    for run in badge_p.runs:
        run.font.size = Pt(12)
        run.font.bold = True
        run.font.color.rgb = RGBColor(255, 255, 255)

    # ---- Slide 2: Planogram visual ----
    slide_two = prs.slides.add_slide(blank_layout)

    header_box = slide_two.shapes.add_textbox(Inches(0.4), Inches(0.2), Inches(12.5), Inches(0.5))
    header_p = header_box.text_frame.paragraphs[0]
    header_p.text = _store_label(planogram_json, store_name)
    for run in header_p.runs:
        run.font.size = Pt(20)
        run.font.bold = True
        run.font.color.rgb = RGBColor(26, 35, 50)

    canvas_left = Inches(1.4)
    canvas_top = Inches(1.0)
    canvas_width = Inches(11.5)
    canvas_height = Inches(6.0)
    shelf_height = canvas_height // max(shelf_count, 1)

    sorted_shelves = sorted(shelves, key=lambda s: int(s.get("shelf_number") or 0))

    for index, shelf in enumerate(sorted_shelves):
        shelf_top = canvas_top + shelf_height * index

        # Shelf label
        label_box = slide_two.shapes.add_textbox(Inches(0.2), shelf_top + Inches(0.1), Inches(1.1), Inches(0.5))
        label_p = label_box.text_frame.paragraphs[0]
        tier_label = TIER_LABELS.get(str(shelf.get("tier") or "mid_level"), "Mid Level")
        label_p.text = f"Shelf {shelf.get('shelf_number')}\n{tier_label}"
        for run in label_p.runs:
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor(74, 85, 104)

        # Shelf base line (rectangle as separator)
        line = slide_two.shapes.add_shape(
            MSO_SHAPE.RECTANGLE, canvas_left, shelf_top + shelf_height - Emu(20000), canvas_width, Emu(20000)
        )
        line.fill.solid()
        line.fill.fore_color.rgb = RGBColor(204, 204, 204)
        line.line.fill.background()

        for product in shelf.get("products") or []:
            position_x_cm = float(product.get("position_x_cm") or 0.0)
            total_width_cm = float(product.get("total_width_cm") or product.get("width_cm") or 10.0)

            x = canvas_left + Emu(int((position_x_cm / shelf_width_cm) * int(canvas_width)))
            w = Emu(max(50000, int((total_width_cm / shelf_width_cm) * int(canvas_width))))
            y = shelf_top + Emu(40000)
            h = shelf_height - Emu(80000)

            shape = slide_two.shapes.add_shape(MSO_SHAPE.RECTANGLE, x, y, w, h)
            color_hex = str(product.get("color_hex") or "#95A5A6")
            _set_shape_fill(shape, color_hex)
            _set_shape_text(
                shape,
                str(product.get("sku") or ""),
                str(product.get("name") or ""),
                int(product.get("facing_count") or 1),
                _is_dark(_hex_to_rgb(color_hex)),
            )

    # ---- Slide 3: Summary ----
    slide_three = prs.slides.add_slide(blank_layout)

    title_box_3 = slide_three.shapes.add_textbox(Inches(0.5), Inches(0.3), Inches(12.0), Inches(0.6))
    p = title_box_3.text_frame.paragraphs[0]
    p.text = "Planogram Summary"
    for run in p.runs:
        run.font.size = Pt(28)
        run.font.bold = True
        run.font.color.rgb = RGBColor(26, 35, 50)

    # Category table
    rows = len(category_summary) + 1
    if rows > 1:
        cols = 4
        table_shape = slide_three.shapes.add_table(rows, cols, Inches(0.5), Inches(1.2), Inches(7.5), Inches(0.4) * rows)
        table = table_shape.table
        headers = ["Category", "SKU Count", "Total Revenue", "Shelves"]
        for col_idx, header in enumerate(headers):
            cell = table.cell(0, col_idx)
            cell.text = header
            for run in cell.text_frame.paragraphs[0].runs:
                run.font.bold = True
                run.font.size = Pt(11)
        for row_idx, (category, values) in enumerate(category_summary.items(), start=1):
            table.cell(row_idx, 0).text = str(category).title()
            table.cell(row_idx, 1).text = str(values.get("sku_count", 0))
            table.cell(row_idx, 2).text = f"{float(values.get('total_revenue', 0)):,.2f}"
            table.cell(row_idx, 3).text = ", ".join(str(s) for s in values.get("shelves") or [])
            for col_idx in range(cols):
                for run in table.cell(row_idx, col_idx).text_frame.paragraphs[0].runs:
                    run.font.size = Pt(10)

    # Right column: assortment + warnings
    info_box = slide_three.shapes.add_textbox(Inches(8.3), Inches(1.2), Inches(4.7), Inches(6.0))
    info_tf = info_box.text_frame
    info_tf.word_wrap = True
    head = info_tf.paragraphs[0]
    head.text = "Assortment"
    for run in head.runs:
        run.font.bold = True
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(26, 35, 50)

    line_p = info_tf.add_paragraph()
    line_p.text = (
        f"Showing {assortment.get('included_skus', 0)} of {assortment.get('total_catalogue_skus', 0)} catalogue SKUs"
    )
    for run in line_p.runs:
        run.font.size = Pt(11)

    if assortment.get("message"):
        msg_p = info_tf.add_paragraph()
        msg_p.text = str(assortment.get("message"))
        for run in msg_p.runs:
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(74, 85, 104)

    spacer = info_tf.add_paragraph()
    spacer.text = ""

    head2 = info_tf.add_paragraph()
    head2.text = "Data Quality Warnings"
    for run in head2.runs:
        run.font.bold = True
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(26, 35, 50)

    if not warnings:
        clear_p = info_tf.add_paragraph()
        clear_p.text = "No warnings — data quality looks healthy."
        for run in clear_p.runs:
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(74, 85, 104)
    else:
        for warning in warnings:
            wp = info_tf.add_paragraph()
            severity = str(warning.get("severity") or "low").upper()
            wp.text = f"[{severity}] {warning.get('message') or ''}"
            for run in wp.runs:
                run.font.size = Pt(10)
                color = {
                    "HIGH": RGBColor(231, 76, 60),
                    "MEDIUM": RGBColor(243, 156, 18),
                    "LOW": RGBColor(74, 85, 104),
                }.get(severity, RGBColor(74, 85, 104))
                run.font.color.rgb = color

    buffer = io.BytesIO()
    prs.save(buffer)
    return buffer.getvalue()
