from typing import Literal

ROLE_ADMIN = "admin"
ROLE_MERCHANDISER = "merchandiser"
ROLE_MERCHANDISER_PRO = "merchandiser-pro"
ROLE_ENTERPRISE = "enterprise"

VALID_ROLES = [ROLE_ADMIN, ROLE_MERCHANDISER, ROLE_MERCHANDISER_PRO, ROLE_ENTERPRISE]
ROLE_TYPE = Literal["admin", "merchandiser", "merchandiser-pro", "enterprise"]
VALID_SIGNUP_ROLES = [ROLE_MERCHANDISER, ROLE_MERCHANDISER_PRO, ROLE_ENTERPRISE]
SIGNUP_ROLE_TYPE = Literal["merchandiser", "merchandiser-pro", "enterprise"]

TIER_ADMIN = "admin"
TIER_INDIVIDUAL_PLUS = "individual-plus"
TIER_INDIVIDUAL_PRO = "individual-pro"
TIER_ENTERPRISE = "enterprise"

VALID_TIERS = [TIER_ADMIN, TIER_INDIVIDUAL_PLUS, TIER_INDIVIDUAL_PRO, TIER_ENTERPRISE]
TIER_TYPE = Literal["admin", "individual-plus", "individual-pro", "enterprise"]

ROLE_TO_DEFAULT_TIER = {
    ROLE_ADMIN: TIER_ADMIN,
    ROLE_MERCHANDISER: TIER_INDIVIDUAL_PLUS,
    ROLE_MERCHANDISER_PRO: TIER_INDIVIDUAL_PRO,
    ROLE_ENTERPRISE: TIER_ENTERPRISE,
}

SEED_ADMIN_EMAIL = "admin@aexiz.com"
SEED_ADMIN_PASSWORD = "qwerty123"

DEFAULT_PLAN_LIMITS = {
    TIER_ADMIN: None,
    TIER_INDIVIDUAL_PLUS: 15,
    TIER_INDIVIDUAL_PRO: 45,
    TIER_ENTERPRISE: None,
}

ERROR_CODE_QUOTA_EXCEEDED = "quota_exceeded"
ERROR_CODE_INVALID_CREDENTIALS = "invalid_credentials"
ERROR_CODE_EMAIL_EXISTS = "email_exists"
ERROR_CODE_USERNAME_EXISTS = "username_exists"
ERROR_CODE_UNAUTHORIZED = "unauthorized"
ERROR_CODE_FORBIDDEN = "forbidden"
